### ISSUE TITLE
Jelly UVs

### ISSUE THREAD

**Issue by ThibaultGROUEIX** [crisrom002/hsd-learning-contact-corrections#1]
Hi @crisrom002 ,

Thank you for providing the data and taking the time to make this very clear README. I am building towards a comparison with your paper.
Could you kindly provide the UV parameterisation of the JELLY and STAR mesh? 
If you can, the code snippet to plot with texture would be ideal!

Thanks a lot,
Thibault

**Comment by crisrom002** [comment]
Hi @ThibaultGROUEIX ,

We have extended the meshes.h5 file with the UV coordinates and indices corresponding to the JELLY mesh. The STAR mesh is using a uniform color in our paper renders, so it does not require any UV parameterization.

I hope you find it useful,
Cristian.

**Comment by ThibaultGROUEIX** [comment]
I do not understand.
Sorry if i am missing something obvious but I cannot find the UV coordinates of the JELLY mesh in your repo. Where did you get it?
Thanks for your help!

**Comment by crisrom002** [comment]
You have to download the meshes.h5 file from the [[Data]](https://urjc-my.sharepoint.com/personal/cristian_romero_urjc_es/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fcristian%5Fromero%5Furjc%5Fes%2FDocuments%2FLearning%20Contact%20Corrections%20for%20Handle%2DBased%20Subspace%20Dynamics%2FjellyObject%5FstarCollider%2Fdata) directory.

As explained in the [visualization section](https://github.com/crisrom002/hsd-learning-contact-corrections#visualization) of the README, this file contains the UV coordinates and UV indices for the JELLY. The corresponding keys are `uv_coords` and `uv_indices`.

I have included in the assets directory a reference `.obj` file for the JELLY, containing the same UV coordinates / indices. Maybe this format is more useful for you.

**Comment by ThibaultGROUEIX** [comment]
Thanks! I did not see your latest commit, thanks again!
